export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SET_LOADING = 'SET_LOADING'
export const END_LOADING = 'END_LOADING'

export const SET_ADD_FOOD = 'SET_ADD_FOOD'

export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS'
export const GET_DETAILS_BEGIN = 'GET_DETAILS_BEGIN'
export const GET_DETAILS_ERROR = 'GET_DETAILS_ERROR'

export const ADD_FOOD_BEGIN = 'ADD_FOOD_BEGIN'
export const ADD_FOOD_SUCCESS = 'ADD_FOOD_SUCCESS'
export const ADD_FOOD_ERROR = 'ADD_FOOD_ERROR'

export const GET_FOODS_BEGIN = 'GET_FOODS_BEGIN'
export const GET_FOODS_SUCCESS = 'GET_FOODS_SUCCESS'
export const GET_FOODS_ERROR = 'GET_FOODS_ERROR'

export const SET_EDIT_FOOD = 'SET_EDIT_FOOD'

export const EDIT_FOOD_BEGIN = 'EDIT_FOOD_BEGIN'
export const EDIT_FOOD_SUCCESS = 'EDIT_FOOD_SUCCESS'
export const EDIT_FOOD_ERROR = 'EDIT_FOOD_ERROR'

export const DELETE_FOOD_BEGIN = 'DELETE_FOOD_BEGIN'
export const DELETE_FOOD_SUCCESS = 'DELETE_FOOD_SUCCESS'
export const DELETE_FOOD_ERROR = 'DELETE_FOOD_ERROR'

export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const GET_NEXT_DAY = 'GET_NEXT_DAY'
export const GET_PREV_DAY = 'GET_PREV_DAY'

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN'
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'
